name             'aws-ciaas'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures ciaas'
long_description 'Installs/Configures ciaas'
version          '0.1.0'
